var boardtheme = {  

    "info":null,
    "landables":[  
        {  
            "type":"GenericLandableArea",
            "name":"Go"
        },
        {  
            "type":"Street",
            "name":"Northshire\nAbbey",
            "cost":60,
            "rent":[  
                4,
                100,
                200,
                300,
                400,
                600
            ],
            "color":"#955436",
            "houseCost":200,
            "mortgageVal":150
        },
        {  
            "type":"GenericLandableArea",
            "name":"Community\nChest"
        },
        {  
            "type":"Street",
            "name":"Goldshire",
            "cost":60,
            "rent":[  
                4,
                100,
                200,
                300,
                400,
                600
            ],
            "color":"#955436",
            "houseCost":200,
            "mortgageVal":150
        },
        {  
            "type":"GenericLandableArea",
            "name":"Income Tax"
        },
        {  
            "type":"Railroad",
            "name":"Deeprun Tram\n Stormwind",
            "cost":200,
            "rent":[  
                25,
                50,
                100,
                200
            ],
            "mortgageVal":150
        },
        {  
            "type":"Street",
            "name":"Deathknell",
            "cost":100,
            "rent":[  
                6,
                100,
                200,
                300,
                400,
                600
            ],
            "color":"#A8E2F8",
            "houseCost":200,
            "mortgageVal":150
        },
        {  
            "type":"GenericLandableArea",
            "name":"Chance"
        },
        {  
            "type":"Street",
            "name":"Brill",
            "cost":100,
            "rent":[  
                6,
                100,
                200,
                300,
                400,
                600
            ],
            "color":"#A8E2F8",
            "houseCost":200,
            "mortgageVal":150
        },
        {  
            "type":"Street",
            "name":"The Speculcher",
            "cost":120,
            "rent":[  
                8,
                100,
                200,
                300,
                400,
                600
            ],
            "color":"#A8E2F8",
            "houseCost":200,
            "mortgageVal":150
        },
        {  
            "type":"GenericLandableArea",
            "name":"Just Visiting /\nGo To Jail"
        },
        {  
            "type":"Street",
            "name":"Anvilmar",
            "cost":140,
            "rent":[  
                8,
                100,
                200,
                300,
                400,
                600
            ],
            "color":"#D93A96",
            "houseCost":200,
            "mortgageVal":150
        },
        {  
            "type":"Utility",
            "name":"Gold Mine",
            "cost":150,
            "rentFactor":[  
                4,
                10
            ],
            "mortgageVal":100
        },
        {  
            "type":"Street",
            "name":"Khranos",
            "cost":140,
            "rent":[  
                8,
                100,
                200,
                300,
                400,
                600
            ],
            "color":"#D93A96",
            "houseCost":200,
            "mortgageVal":150
        },
        {  
            "type":"Street",
            "name":"Amberstill\nRanch",
            "cost":160,
            "rent":[  
                8,
                100,
                200,
                300,
                400,
                600
            ],
            "color":"#D93A96",
            "houseCost":200,
            "mortgageVal":150
        },
        {  
            "type":"Railroad",
            "name":"Deeprun Tram\nIrongorge",
            "cost":200,
            "rent":[  
                25,
                50,
                100,
                200
            ],
            "mortgageVal":150
        },
        {  
            "type":"Street",
            "name":"Sunstrider Isle",
            "cost":180,
            "rent":[  
                10,
                100,
                200,
                300,
                400,
                600
            ],
            "color":"#F7941D",
            "houseCost":200,
            "mortgageVal":150
        },
        {  
            "type":"GenericLandableArea",
            "name":"Community\nChest"
        },
        {  
            "type":"Street",
            "name":"Farstrider\nRetreat",
            "cost":180,
            "rent":[  
                10,
                100,
                200,
                300,
                400,
                600
            ],
            "color":"#F7941D",
            "houseCost":200,
            "mortgageVal":150
        },
        {  
            "type":"Street",
            "name":"Fairbreeze\nVillage",
            "cost":200,
            "rent":[  
                12,
                100,
                200,
                300,
                400,
                600
            ],
            "color":"#F7941D",
            "houseCost":200,
            "mortgageVal":150
        },
        {  
            "type":"GenericLandableArea",
            "name":"Free Parking"
        },
        {  
            "type":"Street",
            "name":"Valley of Trials",
            "cost":220,
            "rent":[  
                18,
                100,
                200,
                300,
                400,
                600
            ],
            "color":"#ED1B24",
            "houseCost":200,
            "mortgageVal":150
        },
        {  
            "type":"GenericLandableArea",
            "name":"Chance"
        },
        {  
            "type":"Street",
            "name":"Razor Hill",
            "cost":220,
            "rent":[  
                18,
                100,
                200,
                300,
                400,
                600
            ],
            "color":"#ED1B24",
            "houseCost":200,
            "mortgageVal":150
        },
        {  
            "type":"Street",
            "name":"The Crossroads",
            "cost":240,
            "rent":[  
                20,
                100,
                200,
                300,
                400,
                600
            ],
            "color":"#ED1B24",
            "houseCost":200,
            "mortgageVal":150
        },
        {  
            "type":"Railroad",
            "name":"Orgrimmar\nZeplin",
            "rent":[  
                25,
                50,
                100,
                200
            ],
            "mortgageVal":150
        },
        {  
            "type":"Street",
            "name":"Nessingwary\nExpedition",
            "cost":260,
            "rent":[  
                8,
                100,
                200,
                300,
                400,
                600
            ],
            "color":"#FEF200",
            "houseCost":200,
            "mortgageVal":150
        },
        {  
            "type":"Street",
            "name":"Venture Co.\nBase Camp",
            "cost":260,
            "rent":[  
                8,
                100,
                200,
                300,
                400,
                600
            ],
            "color":"#FEF200",
            "houseCost":200,
            "mortgageVal":150
        },
        {  
            "type":"Utility",
            "name":"Lumber Mill",
            "cost":150,
            "rentFactor":[  
                4,
                10
            ],
            "mortgageVal":100
        },
        {  
            "type":"Street",
            "name":"Booty Bay",
            "cost":280,
            "rent":[  
                8,
                100,
                200,
                300,
                400,
                600
            ],
            "color":"#FEF200",
            "houseCost":200,
            "mortgageVal":150
        },
        {  
            "type":"GenericLandableArea",
            "name":"Go To Jail"
        },
        {  
            "type":"Street",
            "name":"Dolonar",
            "cost":300,
            "rent":[  
                8,
                100,
                200,
                300,
                400,
                600
            ],
            "color":"#1FB25A",
            "houseCost":200,
            "mortgageVal":150
        },
        {  
            "type":"Street",
            "name":"Rut'theran\nVillage",
            "cost":300,
            "rent":[  
                8,
                100,
                200,
                300,
                400,
                600
            ],
            "color":"#1FB25A",
            "houseCost":200,
            "mortgageVal":150
        },
        {  
            "type":"GenericLandableArea",
            "name":"Community\nChest"
        },
        {  
            "type":"Street",
            "name":"Darkshore",
            "cost":320,
            "rent":[  
                8,
                100,
                200,
                300,
                400,
                600
            ],
            "color":"#1FB25A",
            "houseCost":200,
            "mortgageVal":150
        },
        {  
            "type":"Railroad",
            "name":"Zepplin\nUndercity",
            "cost":200,
            "rent":[  
                25,
                50,
                100,
                200
            ],
            "mortgageVal":150
        },
        {  
            "type":"GenericLandableArea",
            "name":"Chance"
        },
        {  
            "type":"Street",
            "name":"Dalaran",
            "cost":350,
            "rent":[  
                10,
                100,
                200,
                300,
                400,
                600
            ],
            "color":"#0072BB",
            "houseCost":200,
            "mortgageVal":150
        },
        {  
            "type":"GenericLandableArea",
            "name":"Luxury Tax"
        },
        {  
            "type":"Street",
            "name":"Pandaria",
            "cost":400,
            "rent":[  
                10,
                100,
                200,
                300,
                400,
                600
            ],
            "color":"#0072BB",
            "houseCost":200,
            "mortgageVal":150
        }
    ]
}